name: ejemplo_clean_architecture_tdd
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  
uses-material-design: true

